### ISSUE TITLE
S3PParserBase: неэффективная работа

### ISSUE THREAD

**Issue by CuberHuber** [S3-Platform-Inc/s3p-sdk#10]
Метод `_find` класса `S3PParserBase` работает неэффективно. Нужно добавить проверку того, что полученный материал является последним необходимым. 

Возможно стоит внести этот код в if statement c `_max_documents`. В таком случае, если полученный материал будет последним необходимым, то он добавиться в `_parsed_document` и затем вернет `S3PPluginParserFinish`

```python
    def _find(self, document: S3PDocument):
        """
        A method of checking that the number of documents has exceeded the maximum number or the found document is
        equal to the last document
        """
        if self._last_document is not None and self._last_document.hash == document.hash:
            raise S3PPluginParserFinish(self._plugin, f"Find already existing document ({self._last_document.to_logging})")

        if self._max_documents is not None and len(self._parsed_document) >= self._max_documents:
            raise S3PPluginParserFinish(self._plugin, f"Max count articles reached ({self._max_documents})")

        self._parsed_document.append(document)
        self.logger.info(f'Find '+document.to_logging)
```

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the _find method in S3PParserBase to check if the current document is the last necessary one. Added import for S3PPluginParserFinish exception and updated the logic to raise this exception when appropriate.

You can review changes in this commit: https://github.com/lattaai12/S3-Platform-Inc-s3p-sdk-10/commit/5d3c30f830db2c1343d8b102e1fe3ab745e26305.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
